const images = [
    'Abra',
    'Alakazam',
    'Arbok',
    'Arcanine',
    'Beedrill',
    'Bellsprout',
    'Blastoise',
    'Bulbasaur',
    // 'Butterfree',
    // 'Caterpie',
    // 'Charizard',
    // 'Charmander',
    // 'Charmeleon',
    // 'Clefable',
    // 'Clefairy',
    // 'Cloyster',
    // 'Dewgong',
    // 'Diglett',
    // 'Dodrio',
    // 'Doduo',
    // 'Drowzee',
    // 'Dugtrio',
    // 'Ekans',
    // 'Farfetchd',
    // 'Fearow',
    // 'Gastly',
    // 'Gengar',
    // 'Geodude',
    // 'Gloom',
    // 'Golbat',
    // 'Golduck',
    // 'Golem',
    // 'Graveler',
    // 'Grimer',
    // 'Growlithe',
    // 'Haunter',
    // 'Hypno',
    // 'Ivysaur',
    // 'Jigglypuff',
    // 'Kadabra',
    // 'Kakuna',
    // 'Kingler',
    // 'Krabby',
    // 'Machamp',
    // 'Machoke',
    // 'Machop',
    // 'Magnemite',
    // 'Magneton',
    // 'Mankey',
    // 'Meowth',
    // 'Metapod',
    // 'Muk',
    // 'Nidoking',
    // 'Nidoqueen',
    // 'Nidoran',
    // 'NidoranFemea',
    // 'Nidorina',
    // 'Nidorino',
    // 'Ninetales',
    // 'Oddish',
    // 'Onix',
    // 'Paras',
    // 'Parasect',
    // 'Persian',
    // 'Pidgeot',
    // 'Pidgeotto',
    // 'Pidgey',
    // 'Pikachu',
    // 'Poliwag',
    // 'Poliwhirl',
    // 'Poliwrath',
    // 'Ponyta',
    // 'Primeape',
    // 'Psyduck',
    // 'Raichu',
    // 'Rapidash',
    // 'Raticate',
    // 'Rattata',
    // 'Sandshrew',
    // 'Sandslash',
    // 'Seel',
    // 'Shellder',
    // 'Slowbro',
    // 'Slowpoke',
    // 'Spearow',
    // 'Squirtle',
    // 'Tentacool',
    // 'Tentacruel',
    // 'Venomoth',
    // 'Venonat',
    // 'Venusaur',
    // 'Victreebel',
    // 'Vileplume',
    // 'Voltorb',
    // 'Vulpix',
    // 'Wartortle',
    // 'Weedle',
    // 'Weepinbell',
    // 'Wigglytuff',
    // 'Zubat',
];

const uniqueCards = images.map((
    images,
    idPair
) => ({
    idPair,
    images,
}));

export const pairOfCards = [
    ...uniqueCards,
    ...uniqueCards
].map((
    card,
    id
) => ({

    ...card, id
})

);